/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    'event-series': EventSery;
    events: Event;
    'event-locations': EventLocation;
    organizations: Organization;
    projects: Project;
    teams: Team;
    profiles: Profile;
    'profile-skills': ProfileSkill;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  authId: string;
  name: string;
  role: 'admin' | 'organization' | 'volunteer' | 'board-member';
  phone?: string | null;
  organization?: (string | null) | Organization;
  profile?: (string | null) | Profile;
  notes?: string | null;
  archived?: boolean | null;
  'archived-date'?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  projects?: (string | Project)[] | null;
  name: string;
  description?: string | null;
  address: {
    'address-line1': string;
    'address-line2'?: string | null;
    city: string;
    state:
      | 'AL'
      | 'AK'
      | 'AZ'
      | 'AR'
      | 'CA'
      | 'CO'
      | 'CT'
      | 'DE'
      | 'FL'
      | 'GA'
      | 'HI'
      | 'ID'
      | 'IL'
      | 'IN'
      | 'IA'
      | 'KS'
      | 'KY'
      | 'LA'
      | 'ME'
      | 'MD'
      | 'MA'
      | 'MI'
      | 'MN'
      | 'MS'
      | 'MO'
      | 'MT'
      | 'NE'
      | 'NV'
      | 'NH'
      | 'NJ'
      | 'NM'
      | 'NY'
      | 'NC'
      | 'ND'
      | 'OH'
      | 'OK'
      | 'OR'
      | 'PA'
      | 'RI'
      | 'SC'
      | 'SD'
      | 'TN'
      | 'TX'
      | 'UT'
      | 'VT'
      | 'VA'
      | 'WA'
      | 'WV'
      | 'WI'
      | 'WY';
    'postal-code': string;
  };
  website: string;
  contacts?:
    | {
        name: string;
        'primary-contact'?: boolean | null;
        'phone-number'?: string | null;
        email?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  teams?: (string | Team)[] | null;
  'brief-description': string;
  'extended-description'?: string | null;
  'project-size'?: ('xs' | 's' | 'm' | 'l' | 'xl') | null;
  'team-size'?: ('xs' | 's' | 'm' | 'l' | 'xl') | null;
  'key-skills'?: string | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  roles: {
    description: string;
    notes?: string | null;
    id?: string | null;
  }[];
  'team-lead': (string | User)[];
  'team-members'?:
    | {
        volunteer?: (string | null) | User;
        role: string;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: string;
  completionDate?: string | null;
  lastUpdated: string;
  roles?: ('designer' | 'developer' | 'support' | 'lead')[] | null;
  linkedInUrl?: string | null;
  websiteUrl?: string | null;
  portfolioUrl?: string | null;
  shirtSize?: ('small' | 'medium' | 'large' | 'xl' | 'xxl' | '3xl' | '4xl' | '5xl') | null;
  dietaryRestrictions?:
    | ('vegan' | 'vegetarian' | 'dairy' | 'gluten' | 'kosher' | 'nuts' | 'fish' | 'eggs' | 'soy' | 'corn' | 'other')
    | null;
  additionalDietaryRestrictions?: string | null;
  accessibilityRequirements?: string | null;
  agreements?: {
    codeOfConduct?: {
      version?: string | null;
      date?: string | null;
    };
    photoRelease?: {
      version?: string | null;
      date?: string | null;
    };
    termsAndConditions?: {
      version?: string | null;
      date?: string | null;
    };
  };
  skills?:
    | {
        skill: string | ProfileSkill;
        level: '0' | '1' | '2' | '3' | '4';
        id?: string | null;
      }[]
    | null;
  additionalSkills?: string | null;
  teamLeadCandidate?: boolean | null;
  previousVolunteer?: boolean | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile-skills".
 */
export interface ProfileSkill {
  id: string;
  code: string;
  description: string;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-series".
 */
export interface EventSery {
  id: string;
  event?: (string | Event)[] | null;
  name: string;
  description?: string | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  projects?: (string | Project)[] | null;
  name: string;
  'start-date': string;
  'end-date': string;
  description?: string | null;
  location?: (string | null) | EventLocation;
  'is-virtual'?: boolean | null;
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-locations".
 */
export interface EventLocation {
  id: string;
  name: string;
  description?: string | null;
  address: {
    'address-line1': string;
    'address-line2'?: string | null;
    city: string;
    state:
      | 'AL'
      | 'AK'
      | 'AZ'
      | 'AR'
      | 'CA'
      | 'CO'
      | 'CT'
      | 'DE'
      | 'FL'
      | 'GA'
      | 'HI'
      | 'ID'
      | 'IL'
      | 'IN'
      | 'IA'
      | 'KS'
      | 'KY'
      | 'LA'
      | 'ME'
      | 'MD'
      | 'MA'
      | 'MI'
      | 'MN'
      | 'MS'
      | 'MO'
      | 'MT'
      | 'NE'
      | 'NV'
      | 'NH'
      | 'NJ'
      | 'NM'
      | 'NY'
      | 'NC'
      | 'ND'
      | 'OH'
      | 'OK'
      | 'OR'
      | 'PA'
      | 'RI'
      | 'SC'
      | 'SD'
      | 'TN'
      | 'TX'
      | 'UT'
      | 'VT'
      | 'VA'
      | 'WA'
      | 'WV'
      | 'WI'
      | 'WY';
    'postal-code': string;
  };
  notes?: string | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'event-series';
        value: string | EventSery;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'event-locations';
        value: string | EventLocation;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'profiles';
        value: string | Profile;
      } | null)
    | ({
        relationTo: 'profile-skills';
        value: string | ProfileSkill;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}